<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>Python错误处理 - Tiiktak&#39;s</title>
    
    <meta name="description" content="在Python中也同样使用try...except...finally...的错误处理机制
try except try: print(&#39;try...&#39;) r = 10/0 print(&#39;result:&#39;, r) except ZeroDivisionError as e: print(&#39;except:&#39;, e) finally: print(&#39;finally...&#39;) print(&#39;END&#39;)  当认为某一块代码有错误时，就可以用try来运行该段代码，若执行出错，则后续代码不会执行，而会跳转到except块，执行完except后，若后续有finally片段，则执行finally块
上面的代码中有一个除0的错误，运行结果:
try... except: division by zero finally... END  当计算r后，捕捉到ZeroDivisionError错误，执行 except语句段，之后执行finally
else 可以在except后面加上else，当没有错误发生时将执行else语句块
try: print(&#39;try...&#39;) r = 10/5 print(&#39;result:&#39;, r) except ZeroDivisionError as e: print(&#39;except:&#39;, e) else: print(&#39;no error&#39;) print(&#39;END&#39;)  结果:
try... result: 2.0 no error END   Python的错误是一个class，所有错误类型都继承自BaseException，故使用except时需注意它会也会捕获该类型的子类。
 常见错误类型及继承关系（中文）：官方文档 ```
  优势 使用try...except捕获错误还有一个巨大的好处，就是可以跨越多层调用，比如函数main()调用fun()，fun()调用bar()，结果bar()出错了，这时，只要main()捕获到了，就可以处理">
    <meta name="author" content="">
    
    <link href="https://konosuba.xyz/css/github-gist.min.css" rel="stylesheet">
    <link href="https://konosuba.xyz/css/style.css" rel="stylesheet">
    
    <link rel="apple-touch-icon" href="https://konosuba.xyz/img/apple-touch-icon.png">
    <link rel="icon" href="https://konosuba.xyz/img/favicon.ico">
    
    <meta name="generator" content="Hugo 0.55.6" />
    
    <link rel="alternate" type="application/atom+xml" href="https://konosuba.xyz/index.xml" title="Tiiktak&#39;s">
    
    
    
    
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-141514532-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() { dataLayer.push(arguments); }
      gtag('js', new Date());

      gtag('config', 'UA-141514532-1');
    </script>
    
    <script>
      var _hmt = _hmt || [];
      (function () {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?0121c6813b611028681cd70e85594cb6";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();
    </script>

  </head>
  <body class="single">
    <header class="header">
      <div class="wrap">
        
        <p class="logo"><a href="https://konosuba.xyz/">Tiiktak&#39;s</a></p>
        
        
        <button class="menu-toggle" type="button"></button>
        
      </div>
    </header>
    
    <nav class="nav">
      <ul class="menu">
        
        <li>
          <a href="/about/">About</a>
        </li>
        
      </ul>
    </nav>
    
    <main class="main">


<article class="post-single">
  <header class="post-header">
    <h1 class="post-title">Python错误处理</h1>
    <div class="post-meta">2019.9.6</div>
  </header>
  <div class="post-content">

<p>在Python中也同样使用<code>try...except...finally...</code>的错误处理机制</p>

<h1 id="try">try</h1>

<h2 id="except">except</h2>

<pre><code class="language-py">try:
    print('try...')
    r = 10/0
    print('result:', r)
except ZeroDivisionError as e:
    print('except:', e)
finally:
    print('finally...')
print('END')
</code></pre>

<p>当认为某一块代码有错误时，就可以用<code>try</code>来运行该段代码，若执行出错，则后续代码不会执行，而会跳转到<code>except</code>块，执行完<code>except</code>后，若后续有<code>finally</code>片段，则执行<code>finally</code>块</p>

<p>上面的代码中有一个除0的错误，运行结果:</p>

<pre><code>try...
except: division by zero 
finally...
END
</code></pre>

<p>当计算r后，捕捉到<code>ZeroDivisionError</code>错误，执行   <code>except</code>语句段，之后执行<code>finally</code></p>

<h2 id="else">else</h2>

<p>可以在<code>except</code>后面加上<code>else</code>，当没有错误发生时将执行<code>else</code>语句块</p>

<pre><code class="language-py">try:
    print('try...')
    r = 10/5
    print('result:', r)
except ZeroDivisionError as e:
    print('except:', e)
else:
	print('no error')
print('END')
</code></pre>

<p>结果:</p>

<pre><code>try...
result: 2.0
no error
END
</code></pre>

<blockquote>
<p>Python的错误是一个class，所有错误类型都继承自<code>BaseException</code>，故使用<code>except</code>时需注意它会也会捕获该类型的子类。</p>

<blockquote>
<p>常见错误类型及继承关系（中文）：<a href="https://docs.python.org/zh-cn/3/library/exceptions.html?highlight=aseexception#BaseException">官方文档</a>
```</p>
</blockquote>
</blockquote>

<h2 id="优势">优势</h2>

<p>使用<code>try...except</code>捕获错误还有一个巨大的好处，就是可以跨越多层调用，比如函数<code>main()</code>调用<code>fun()</code>，<code>fun()</code>调用<code>bar()</code>，结果<code>bar()</code>出错了，这时，只要<code>main()</code>捕获到了，就可以处理</p>

<pre><code class="language-py">def fun(s):
    return 10/int(s)

def bar(s):
    return fun(s) * 2

def main():
    try:
        print('try...')
        bar('0')
    except Exception as e:
        print('Error:', e)
    finally:
        print('finally...')
</code></pre>

<p>结果:</p>

<pre><code>try...
Error: division by zero
finally...
</code></pre>

<h2 id="栈输出">栈输出</h2>

<p>若错误没有被捕捉，会一直往上抛，最终会被Python解释器捕获，打印一个错误信息，之后程序会退出</p>

<p>文件hello.py</p>

<pre><code class="language-py">def fun(s):
    return 10/int(s)

def bar(s):
    return fun(s) * 2

def main():
    bar('0')

main()
</code></pre>

<p>在Python终端中运行文件，输出：</p>

<pre><code class="language-py">Traceback (most recent call last): #错误跟踪信息
  File &quot;hello.py&quot;, line 19, in &lt;module&gt;
    main() #错误原因
  File &quot;hello.py&quot;, line 13, in main
    bar('0')
  File &quot;hello.py&quot;, line 7, in bar
    return fun(s) * 2
  File &quot;hello.py&quot;, line 3, in fun
    return 10/int(s)
ZeroDivisionError: division by zero #错误类型
</code></pre>

<p>错误信息以栈的形式按顺序输出，由此可以找到错误源头</p>

<h2 id="错误记录">错误记录</h2>

<p>可以使用Python内置的<code>logging</code>模块记录错误信息</p>

<pre><code class="language-py">import logging

def fun(s):
    return 10/int(s)

def bar(s):
    return fun(s) * 2

def main():
    try:
        print('try...')
        bar('0')
    except BaseException as e:
        logging.exception(e)
    finally:
        print('finally...')
</code></pre>

<p>这样运行，程序会在打印完错误信息后继续运行：</p>

<pre><code class="language-py">try...
ERROR:root:division by zero
Traceback (most recent call last):
  File &quot;hello.py&quot;, line 16, in main
    bar('0')
  File &quot;hello.py&quot;, line 10, in bar
    return fun(s) * 2
  File &quot;hello.py&quot;, line 6, in fun
    return 10/int(s)
ZeroDivisionError: division by zero
finally...
</code></pre>

<h2 id="抛出错误">抛出错误</h2>

<p>常常使用<code>raise</code>函数抛出错误，当前函数不知道怎么处理错误时，将其向上抛，交给上层函数来处理</p>

<p>|<code>raise</code>语句如果不带参数，就会把当前错误原样抛出。此外在<code>except</code>中<code>raise</code>一个Error，还可以把一种类型的错误转化成另一种类型：</p>

<pre><code class="language-py">try:
    10 / 0
except ZeroDivisionError:
    raise ValueError('input error!')
</code></pre>

<p>只要是合理的转换逻辑即可，但绝不应该将一个<code>IOError</code>转换成毫不相干的<code>ValueError</code></p>
</div>
  <footer class="post-footer">
    
  </footer>
  
  
  
  <div id="disqus_thread"></div>
  <script>
    var disqus_shortname = 'tiiktak';
    (function() {
      var d = document, s = d.createElement('script');
      s.src = 'https://' + disqus_shortname + '.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
    })();
  </script>
  <noscript>
    Please enable JavaScript to view the
    <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
  </noscript>
  
  
  
</article>

</main>
<footer class="footer">
  <span>&copy; 2020 <a href="https://konosuba.xyz/">Tiiktak&#39;s</a></span>
  <span>&middot;</span>
  <span>Powered by <a href="https://gohugo.io/" rel="noopener" target="_blank">Hugo️️</a>️</span>
  <span>&middot;</span>
  <span>Theme️ <a href="https://github.com/nanxiaobei/hugo-paper" rel="noopener" target="_blank">Paper</a></span>
</footer>
<script src="https://konosuba.xyz/js/instantclick.min.js" data-no-instant></script>
<script data-no-instant>InstantClick.init();</script>
<script src="https://konosuba.xyz/js/highlight.min.js" data-no-instant></script>
<script data-no-instant>
  let body;
  function menuToggleListener() {
    body.classList.toggle('blur');
  }
  function setMenuToggleListener() {
    const menuToggle = document.querySelector('.menu-toggle');
    if (!menuToggle) return;
    body = document.querySelector('body');
    menuToggle.addEventListener('click', menuToggleListener);
  }

  hljs.initHighlightingOnLoad();
  setMenuToggleListener();

  InstantClick.on('change', function () {
    document.querySelectorAll('pre code').forEach((block) => {
      hljs.highlightBlock(block);
    });
    setMenuToggleListener();
  });
</script>
</body>
</html>

